export const APP_CONSTANTS = {
  HIT_SLOP: {left: 20, right: 20, top: 20, bottom: 20},
  GRAPH_HEIGHT: 200,
  LOGIN_FORM: 'logIn',
  SIGNUP_FORM: 'signup',
  MORTGAGE_INPUT_FORM: 'MortgageInput',
  FORGOT_PASSWORD_FORM: 'forgotPassword',
  RESET_PASSWORD_FORM: 'resetPassword',
  GENERAL_ERROR: 'Something went wrong!',
  LOG_OUT: 'Logged Out!',
  NOT_AUTHENTICATED_CLASS_NAME: 'NotAuthenticated',
  FALSE_TOKEN: 'FALSE TOKEN',
  MONTH_NAMES: [
    'Jan',
    'Feb',
    'Mar',
    'Apr',
    'May',
    'Jun',
    'Jul',
    'Aug',
    'Sep',
    'Oct',
    'Nov',
    'Dec',
  ],
  DATE_FORMAT: 'YYYY-MM-DD',
  MONTH_NUMBER: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
  LISTENER: {
    DID_FOCUS: 'didFocus',
  },
  LOADER_SIZE: {
    SMALL: 'small',
    LARGE: 'large',
  },
  MIN_GOAL_VALUE: 1,
  SCREEN_TYPE_FORM: 'form',
  KEYBOARD_RETURN_TYPE: {
    DONE: 'done',
    GO: 'go',
  },
  ERROR_STATE_VALUES: {
    EMAIL: 'email',
    PASSWORD: 'password',
  },
  HARD_BACK_PRESS: 'hardwareBackPress',
};
