export const APP_CONSTANTS = {
  HIT_SLOP: {left: 20, right: 20, top: 20, bottom: 20},
  GRAPH_HEIGHT: 200,
  LOGIN_FORM: 'logIn',
  SIGNUP_FORM: 'signup',
  USER_PROFILE_FORM: 'userProfile',
  USER_PROFILE_FORM_VIEW_MODE: 'userProfileViewMode',
  USER_ADDRESS_FORM: 'userAddress',
  MORTGAGE_INPUT_FORM: 'MortgageInput',
  FORGOT_PASSWORD_FORM: 'forgotPassword',
  RESET_PASSWORD_FORM: 'resetPassword',
  GENERAL_ERROR: 'Something went wrong!',
  LOG_OUT: 'Logged Out!',
  NOT_AUTHENTICATED_CLASS_NAME: 'NotAuthenticated',
  FALSE_TOKEN: 'FALSE TOKEN',
  PIN_CELL_COUNT: 5,
  MONTH_NAMES: [
    'Jan',
    'Feb',
    'Mar',
    'Apr',
    'May',
    'Jun',
    'Jul',
    'Aug',
    'Sep',
    'Oct',
    'Nov',
    'Dec',
  ],
  FULL_MONTH_NAMES: [
    'January',
    'February',
    'March',
    'April',
    'May',
    'June',
    'July',
    'August',
    'September',
    'October',
    'November',
    'December',
  ],
  DATE_FORMAT: 'YYYY-MM-DD',
  MONTH_NUMBER: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
  LISTENER: {
    DID_FOCUS: 'didFocus',
  },
  LOADER_SIZE: {
    SMALL: 'small',
    LARGE: 'large',
  },
  MIN_GOAL_VALUE: 1,
  SCREEN_TYPE_FORM: 'form',
  KEYBOARD_RETURN_TYPE: {
    DONE: 'done',
    GO: 'go',
  },
  ERROR_STATE_VALUES: {
    EMAIL: 'email',
    PASSWORD: 'password',
  },
  HARD_BACK_PRESS: 'hardwareBackPress',
  MIN_MORTGAGE_TERM: 1,
  MAX_MORTGAGE_TERM: 35,
  HOME_OWNERSHIP_RANGES: {
    ZERO: 0,
    TWENTY: 20,
    FOURTY: 40,
    SIXTY: 60,
    EIGHTY: 80,
    HUNDRED: 100,
  },
};
