export const NAVIGATION_SCREEN_NAME = {
  AUTH_STACK: 'Auth',
  APP_STACK: 'App',
  LOGIN_SCREEN: 'LoginScreen',
  SIGNUP_SCREEN: 'SignUpScreen',
  DASHBOARD_SCREEN: 'DashboardScreen',
  SET_GOAL_SCREEN: 'SetGoalScreen',
  MORTGAGE_INPUT_SCREEN: 'MortgageInputScreen',
  SAVE_INTEREST_SCREEN: 'SaveInterestScreen',
  TAB_NAVIGATOR: 'TabNavigatorScreen',
  OVERPAYMENT: 'OverPaymentScreen',
  OVERPAYMENT_HISTORY: 'OverpaymentHistoryScreen',
  REPORT_ISSUE: 'ReportIssueScreen',
  UPDATE_MORTGAGE: 'UpdateMortgageScreen',
  INTRO_CAROUSEL: 'IntroCarouselScreen',
  CHECK_EMAIL: 'CheckEmailScreen',
  DEEPLINK_SCREEN: 'DeepLinkLandingScreen',
  ACCOUNT_BLOCKED: 'AccountBlockedScreen',
  FORGOT_PASSWORD: 'ForgotPasswordScreen',
  RESET_PASSWORD: 'ResetPasswordScreen',
  FORGOT_PASSWORD_MAIL: 'PasswordCheckMailScreen',
  UPDATE_PASSWORD: 'UpdatePasswordScreen',
  PUSH_NOTIFICATION: 'PushNotificationScreen',
};
