import {Dimensions, StyleSheet} from 'react-native';

export const STYLE_CONSTANTS = {
  device: {
    SCREEN_HEIGHT: Dimensions.get('screen').height,
    SCREEN_WIDTH: Dimensions.get('screen').width,
    WINDOW_HEIGHT: Dimensions.get('window').height,
    WINDOW_WIDTH: Dimensions.get('window').width,
    DEVICE_TYPE_ANDROID: 'Android',
    DEVICE_TYPE_IOS: 'IOS',
    MAX_WIDTH: '100%',
  },
  elevation: {
    BASIC: 5,
  },
  margin: {
    EXTRA_HUMUNGOUS: 52,
    SLIGHT_HUMUNGOUS: 48,
    HUMONGOUS: 40,
    HUGE: 36,
    HUGER: 32,
    HUGISH: 28,
    LARGER: 24,
    LARGE: 22,
    LARGEST: 20,
    LARGISH: 18,
    NORMAL: 16,
    SMALL: 12,
    SMALLISH: 10,
    SMALLER: 8,
    SMALLEST: 4,
  },
  padding: {
    HUMONGOUS: 44,
    HUGE: 32,
    HUGISH: 28,
    LARGER: 24,
    LARGE: 22,
    LARGEST: 20,
    LARGISH: 18,
    NORMAL: 16,
    BELOW_NORMAL: 14,
    SMALL: 12,
    SMALLISH: 10,
    SMALLER: 8,
    ABOVE_SMALLEST: 6,
    SMALLEST: 4,
  },
  font: {
    SIZE: {
      LARGEST_HUMONGOUS: 52,
      HUMONGOUS: 48,
      HUGEST: 36,
      HUGER: 28,
      HUGE: 24,
      HUGISH: 22,
      LARGEST: 20,
      LARGER: 18,
      LARGE: 16,
      LARGISH: 15,
      NORMAL: 14,
      SMALL: 12,
      SMALLER: 11,
      TINY: 10,
    },
    LINEHEIGHT: {
      LARGEST_HUMONGOUS: 76,
      HUMONGOUS: 48,
      HUGEST: 36,
      HUGER: 28,
      HUGE: 24,
      HUGISH: 22,
      LARGER: 20,
      LARGISH: 18,
      LARGE: 16,
      NORMAL: 14,
      SMALL: 12,
      SMALLER: 11,
    },
    WEIGHT: {
      NORMAL: 'normal',
      SEMI_BOLD: '600',
      BOLD: '900',
    },
  },
  border: {
    WIDTH: {
      LIGHTER: StyleSheet.hairlineWidth, // lighter:0.125,
      LIGHT: StyleSheet.hairlineWidth, // light:0.25,
      NORMAL: StyleSheet.hairlineWidth * 2, // normal:0.5,
      HEAVY: 1, // heavy:1.0,
      HEAVIER: 2, // heavier:1.5,
      HEAVIEST: 3, // heaviest:3,
    },
    BORDER_RADIUS: {
      TINY: 5,
      SMALLER: 8,
    },
  },
  SPLASH_DIMENSION: {
    height: 74,
    width: 222,
  },
  IMAGE_RESIZE_CONFIG: {
    AUTO: 'auto',
    STRETCH: 'stretch',
    CONTAIN: 'contain',
  },
};
