import {StyleSheet, Platform} from 'react-native';
import {STYLE_CONSTANTS, COLOR} from '../../utils';

export const styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
  },
  middleContainer: {},
  passStrengthInnerContainer: {
    marginTop: STYLE_CONSTANTS.margin.SMALLER,
  },
  blueImageBackground: {
    paddingLeft: STYLE_CONSTANTS.padding.HUGISH,
    paddingBottom: STYLE_CONSTANTS.padding.HUMONGOUS,
    paddingRight: STYLE_CONSTANTS.padding.LARGEST,
    paddingTop: Platform.OS === 'android' ? 12 : 0,
  },
  supportIcon: {
    height: STYLE_CONSTANTS.padding.HUMONGOUS,
    width: STYLE_CONSTANTS.padding.HUMONGOUS,
    borderRadius: STYLE_CONSTANTS.padding.HUMONGOUS / 2,
    padding: STYLE_CONSTANTS.padding.SMALLER,
    backgroundColor: COLOR.DARK_VOILET,
    alignSelf: 'flex-end',
    justifyContent: 'center',
    alignItems: 'center',
  },
  bottomImageCard: {
    width:
      10 * STYLE_CONSTANTS.margin.HUMONGOUS - STYLE_CONSTANTS.margin.LARGEST,
    height:
      5 * STYLE_CONSTANTS.margin.HUMONGOUS - STYLE_CONSTANTS.margin.SMALLISH,
    justifyContent: 'center',
  },
  paidButton: {
    height: STYLE_CONSTANTS.margin.LARGER,
    width: STYLE_CONSTANTS.margin.HUMONGOUS,
    backgroundColor: COLOR.LIGHTER_VOILET,
    justifyContent: 'center',
    alignSelf: 'center',
    alignItems: 'center',
    marginLeft: STYLE_CONSTANTS.margin.NORMAL,
    borderRadius: 14,
  },
  targetAmonutContainer: {
    flexDirection: 'row',
    marginTop: STYLE_CONSTANTS.margin.LARGEST,
  },
  targetTextContainer: {justifyContent: 'center'},
  thisMonthText: {
    marginTop: STYLE_CONSTANTS.margin.SMALL,
    fontSize: STYLE_CONSTANTS.font.SIZE.HUGE,
    lineHeight: STYLE_CONSTANTS.font.LINEHEIGHT.HUGEST,
    color: COLOR.WHITE,
    fontWeight: STYLE_CONSTANTS.font.WEIGHT.SEMI_BOLD,
  },
  overPaymentTargetAmount: {
    fontSize: STYLE_CONSTANTS.font.SIZE.HUMONGOUS,
    lineHeight: STYLE_CONSTANTS.font.LINEHEIGHT.LARGEST_HUMONGOUS,
    color: COLOR.WHITE,
    fontWeight: STYLE_CONSTANTS.font.WEIGHT.SEMI_BOLD,
  },
  overPaymentTargetText: {
    fontSize: STYLE_CONSTANTS.font.SIZE.SMALL,
    lineHeight: STYLE_CONSTANTS.font.LINEHEIGHT.HUGE,
    color: COLOR.WHITE,
    opacity: 0.5,
  },
  dueReminderText: {
    fontSize: STYLE_CONSTANTS.font.SIZE.NORMAL,
    lineHeight: STYLE_CONSTANTS.font.LINEHEIGHT.HUGISH,
    color: COLOR.WHITE,
    marginTop: STYLE_CONSTANTS.margin.LARGER,
  },
  secondContainer: {
    marginTop: STYLE_CONSTANTS.margin.LARGEST,
    marginHorizontal: STYLE_CONSTANTS.margin.LARGEST,
  },
  statusContainer: {justifyContent: 'space-between', flexDirection: 'row'},
  statusLefttext: {
    color: COLOR.LIGHT_VOILET,
    fontWeight: STYLE_CONSTANTS.font.WEIGHT.SEMI_BOLD,
  },
  innerFirstText: {color: COLOR.VOILET},
  statusRightText: {color: COLOR.VOILET, opacity: 0.5},
  incomeStatusContainer: {
    borderBottomColor: COLOR.BORDER_BLACK,
    borderColor: COLOR.WHITE,
    borderBottomWidth: 5,
    borderWidth: 1,
    borderRadius: STYLE_CONSTANTS.padding.LARGEST,
    shadowColor: COLOR.BORDER_BLACK,
    shadowOffset: {width: 3, height: 3},
    shadowOpacity: STYLE_CONSTANTS.padding.SMALLISH,
    shadowRadius: STYLE_CONSTANTS.padding.SMALLISH,
  },
  incomeInnerContainer: {
    marginTop: STYLE_CONSTANTS.margin.HUMONGOUS,
    marginHorizontal: STYLE_CONSTANTS.margin.HUGISH,
  },
  rowParentContainer: {flexDirection: 'row'},
  incomeInnerContainers: {alignItems: 'center'},
  incomeText: {
    marginLeft: STYLE_CONSTANTS.margin.SMALLER,
    color: COLOR.PARROT_GREEN,
    fontSize: STYLE_CONSTANTS.font.SIZE.SMALL,
    lineHeight: STYLE_CONSTANTS.font.LINEHEIGHT.HUGISH,
  },
  spentText: {
    marginLeft: STYLE_CONSTANTS.margin.SMALLER,
    color: COLOR.BRICK_RED,
    fontSize: STYLE_CONSTANTS.font.SIZE.SMALL,
    lineHeight: STYLE_CONSTANTS.font.LINEHEIGHT.HUGISH,
  },
  incomeSpentText: {
    color: COLOR.VOILET,
    fontSize: STYLE_CONSTANTS.font.SIZE.HUGE,
    lineHeight: STYLE_CONSTANTS.font.LINEHEIGHT.HUGER,
  },
  availableBalanceText: {
    color: COLOR.VOILET,
    fontSize: STYLE_CONSTANTS.font.SIZE.SMALL,
    lineHeight: STYLE_CONSTANTS.font.LINEHEIGHT.HUGISH,
    opacity: 0.3,
    paddingTop: STYLE_CONSTANTS.padding.HUGE,
    textAlign: 'center',
  },
  availableAmountText: {
    color: COLOR.VOILET,
    fontSize: STYLE_CONSTANTS.font.SIZE.HUGEST,
    /*
  TODO : lineHeight as per XD is less than fontSize, hence cuts upper text, TBD
  */
    textAlign: 'center',
  },
  buttonTitle: {
    color: COLOR.WHITE,
    fontSize: STYLE_CONSTANTS.font.SIZE.LARGE,
    lineHeight: STYLE_CONSTANTS.font.LINEHEIGHT.HUGE,
    paddingVertical: STYLE_CONSTANTS.padding.NORMAL,
    fontWeight: STYLE_CONSTANTS.font.WEIGHT.SEMI_BOLD,
  },
  button: {
    backgroundColor: COLOR.PRIMARY,
    borderRadius: 40,
    marginTop: STYLE_CONSTANTS.margin.HUGISH,
    marginHorizontal: STYLE_CONSTANTS.margin.HUGISH,
  },
  myProgressContainer: {
    marginLeft: STYLE_CONSTANTS.margin.HUGISH,
    marginTop: STYLE_CONSTANTS.margin.HUMONGOUS,
    marginBottom: STYLE_CONSTANTS.margin.LARGEST,
  },
  myProgressText: {
    color: COLOR.VOILET,
    fontSize: STYLE_CONSTANTS.font.SIZE.HUGE,
    lineHeight: STYLE_CONSTANTS.font.LINEHEIGHT.HUGEST,
  },
  projectedText: {
    color: COLOR.LIGHT_VOILET,
    fontSize: STYLE_CONSTANTS.font.SIZE.SMALL,
    lineHeight: STYLE_CONSTANTS.font.LINEHEIGHT.HUGE,
  },
  monthsLeftText: {color: COLOR.VOILET},
  homeOwnerShipCardContainer: {
    flexDirection: 'row',
    paddingHorizontal: STYLE_CONSTANTS.padding.HUGISH,
    paddingVertical: STYLE_CONSTANTS.padding.LARGER,
    justifyContent: 'space-between',
  },
  bottomCardOuterStyle: {
    flex: 1,
    marginHorizontal: STYLE_CONSTANTS.margin.NORMAL,
    marginTop: STYLE_CONSTANTS.margin.EXTRA_HUMUNGOUS,
    marginBottom: STYLE_CONSTANTS.margin.LARGEST,
  },
  badgeContainer: {
    position: 'absolute',
    top: 0,
    right: 0,
    height: STYLE_CONSTANTS.padding.NORMAL,
    width: STYLE_CONSTANTS.padding.NORMAL,
    borderRadius: STYLE_CONSTANTS.padding.NORMAL / 2,
    backgroundColor: COLOR.PRIMARY,
    justifyContent: 'center',
    alignItems: 'center',
  },
  badgeCountText: {
    fontSize: STYLE_CONSTANTS.font.SIZE.SMALL,
    color: COLOR.WHITE,
  },
  bottomCardInnerStyle: {borderRadius: STYLE_CONSTANTS.margin.SMALL},
  ownerShipText: {
    fontSize: STYLE_CONSTANTS.font.SIZE.LARGEST,
    lineHeight: STYLE_CONSTANTS.font.LINEHEIGHT.HUGER,
    color: COLOR.WHITE,
    fontWeight: STYLE_CONSTANTS.font.WEIGHT.SEMI_BOLD,
  },
  viewContainer: {alignItems: 'center', flexDirection: 'row'},
  viewText: {
    fontSize: STYLE_CONSTANTS.font.SIZE.LARGE,
    lineHeight: STYLE_CONSTANTS.font.LINEHEIGHT.HUGE,
    color: COLOR.WHITE,
    fontWeight: STYLE_CONSTANTS.font.WEIGHT.SEMI_BOLD,
    marginRight: STYLE_CONSTANTS.margin.SMALL,
  },
  mainMessageStyle: {
    fontSize: STYLE_CONSTANTS.font.SIZE.HUGEST,
    lineHeight: STYLE_CONSTANTS.font.LINEHEIGHT.HUMONGOUS,
    color: COLOR.CARIBBEAN_GREEN,
    fontWeight: STYLE_CONSTANTS.font.WEIGHT.SEMI_BOLD,
  },
  paymentModalContainer: {
    backgroundColor: COLOR.WHITE,
    borderRadius: 14,
  },
  modalTopContainer: {
    paddingVertical: STYLE_CONSTANTS.padding.SMALL,
    alignItems: 'center',
    paddingHorizontal: STYLE_CONSTANTS.padding.LARGEST,
    borderBottomColor: COLOR.STEEL_GRAY,
    borderBottomWidth: 1,
  },
  stayOnTrackText: {
    textAlign: 'center',
    fontSize: STYLE_CONSTANTS.font.SIZE.NORMAL,
    lineHeight: STYLE_CONSTANTS.font.LINEHEIGHT.LARGER,
    color: COLOR.SHADOW_BLUE,
  },
  overPaymentText: {fontWeight: 'bold'},
  remindMeTomorrowText: {
    paddingVertical: STYLE_CONSTANTS.padding.NORMAL,
    alignItems: 'center',
  },
  laterOptionText: {
    fontSize: STYLE_CONSTANTS.font.SIZE.LARGEST,
    lineHeight: STYLE_CONSTANTS.font.LINEHEIGHT.HUGE,
    color: COLOR.PRIMARY,
  },
  remindMeNextWeekText: {
    paddingVertical: STYLE_CONSTANTS.padding.NORMAL,
    alignItems: 'center',
    borderTopColor: COLOR.STEEL_GRAY,
    borderTopWidth: 1,
  },
  modalDismissContainer: {
    backgroundColor: COLOR.WHITE,
    paddingVertical: STYLE_CONSTANTS.padding.NORMAL,
    borderRadius: 14,
    marginTop: STYLE_CONSTANTS.margin.SMALL,
    alignItems: 'center',
    marginBottom: STYLE_CONSTANTS.margin.LARGEST,
  },
  dismissText: {
    fontSize: STYLE_CONSTANTS.font.SIZE.LARGEST,
    lineHeight: STYLE_CONSTANTS.font.LINEHEIGHT.HUGE,
    color: COLOR.DARK_BLUE,
    fontWeight: STYLE_CONSTANTS.font.WEIGHT.SEMI_BOLD,
  },
});
