export const actionTypes = {
  ADD_USER_DETAILS: 'ADD_USER_DETAILS',
  USER_DATA_CHANGED: 'USER_DATA_CHANGED',
  IS_NOTIFICATION_RECEIVED: 'IS_NOTIFICATION_RECEIVED',
  CLEAR_FORM_DATA: 'CLEAR_FORM_DATA',
  IS_POLICY_UPDATE_RECEIVED: 'IS_POLICY_UPDATE_RECEIVED',
};
